<?php
/**
 * Marketing Needs Survey — AI-generated custom quote.
 *
 * After a submission, the front end requests a personalized plan/quote for
 * the stored entry. The quote is generated by the Claude API (Anthropic),
 * grounded in the survey answers, the rule-based gap analysis, and the
 * service menu / pricing guidance configured under Theme Settings → AI Quote.
 *
 * API key resolution: the DS_ANTHROPIC_API_KEY constant (wp-config.php,
 * recommended) wins over the key stored in the options page.
 */

function ds_survey_ai_api_key() {
    if (defined('DS_ANTHROPIC_API_KEY') && DS_ANTHROPIC_API_KEY) {
        return DS_ANTHROPIC_API_KEY;
    }
    return function_exists('get_field') ? (string) get_field('ai_quote_api_key', 'option') : '';
}

function ds_survey_ai_enabled() {
    if (!function_exists('get_field') || !get_field('ai_quote_enabled', 'option')) return false;
    return (bool) ds_survey_ai_api_key();
}

/**
 * JSON schema the quote must conform to (structured outputs).
 * Keep constraints simple — numeric/string bounds are not supported.
 */
function ds_survey_ai_quote_schema() {
    return [
        'type'       => 'object',
        'properties' => [
            'summary' => [
                'type'        => 'string',
                'description' => "The prospect's situation and biggest opportunity, 2-3 sentences, second person.",
            ],
            'recommendations' => [
                'type'  => 'array',
                'items' => [
                    'type'       => 'object',
                    'properties' => [
                        'service'    => ['type' => 'string', 'description' => 'Service name from the service menu.'],
                        'rationale'  => ['type' => 'string', 'description' => 'Why this service, tied to their specific answers. 1-2 sentences.'],
                        'investment' => ['type' => 'string', 'description' => 'Monthly investment for this service, e.g. "$1,000–$1,500/mo" or "one-time $3,500". Use the service menu pricing.'],
                    ],
                    'required'             => ['service', 'rationale', 'investment'],
                    'additionalProperties' => false,
                ],
            ],
            'total_monthly_investment' => [
                'type'        => 'string',
                'description' => 'Combined recommended monthly investment range, e.g. "$2,500–$4,000/mo".',
            ],
            'expected_outcomes' => [
                'type'        => 'string',
                'description' => 'What this plan is designed to achieve in the first 6-12 months, tied to their goals. 2-3 sentences, no guarantees.',
            ],
            'next_step' => [
                'type'        => 'string',
                'description' => 'One concrete next step, referencing their stated timeline.',
            ],
        ],
        'required'             => ['summary', 'recommendations', 'total_monthly_investment', 'expected_outcomes', 'next_step'],
        'additionalProperties' => false,
    ];
}

/**
 * Build the prompt pair (system, user) for an entry's answers + analysis.
 */
function ds_survey_ai_build_prompt($answers, $analysis) {
    $menu  = function_exists('get_field') ? (string) get_field('ai_quote_service_menu', 'option') : '';
    $extra = function_exists('get_field') ? (string) get_field('ai_quote_instructions', 'option') : '';

    $system = <<<PROMPT
You are a senior marketing strategist at Digital Stride, a digital marketing agency in York, PA that partners with AEC (architecture, engineering, construction) and home service companies. A prospect just completed our marketing needs assessment, and you are preparing their instant preliminary plan and quote. It renders on the thank-you screen they are looking at right now, so write directly to them in second person.

Rules:
- Recommend only services that appear in the service menu below, and take every price from it. If the menu lacks a price for something, express the investment as a range consistent with the prospect's stated budget and revenue — never invent specific prices.
- Scale the total recommended investment to their revenue and stated budget. If their budget is far below what their goals require, recommend a starting scope they can afford and say what to add later.
- Prioritize: fix foundation gaps (website, local visibility, tracking) before recommending more spend on traffic.
- 3 to 5 recommendations, ordered by priority.
- Tie every rationale to their actual answers — quote their situation back to them, don't recite generic benefits.
- Never invent case studies, statistics, client names, or guarantees. Frame outcomes as what the plan is designed to do.
- Plain, confident, jargon-free language. This is a preliminary quote to start a conversation, not a contract.
PROMPT;

    if ($extra !== '') {
        $system .= "\n\nAdditional instructions from the Digital Stride team:\n" . $extra;
    }

    if ($menu === '') {
        $menu = "(No service menu configured — express all investments as ranges consistent with the prospect's budget and revenue, and label them as preliminary estimates.)";
    }

    // Reuse the plain-text renderers from survey.php / survey-analysis.php.
    $config = ds_survey_config();
    $lines  = [];
    foreach ($config as $step) {
        foreach ($step['questions'] as $q) {
            if (!isset($answers[$q['name']])) continue;
            $val     = $answers[$q['name']];
            $lines[] = $q['label'] . ' ' . (is_array($val) ? implode('; ', $val) : $val);
        }
    }

    $user = "SERVICE MENU AND PRICING:\n" . $menu
          . "\n\nPROSPECT'S SURVEY ANSWERS:\n" . implode("\n", $lines)
          . "\n\nAUTOMATED GAP ANALYSIS (rule-based, already shown to the prospect):\n"
          . ds_survey_analysis_text($analysis)
          . "\n\nProduce their preliminary plan and quote.";

    return [$system, $user];
}

/**
 * Call the Claude API and return the decoded quote array, or WP_Error.
 */
function ds_survey_ai_generate_quote($answers, $analysis) {
    $model = function_exists('get_field') ? (string) get_field('ai_quote_model', 'option') : '';
    if ($model === '') $model = 'claude-opus-4-8';

    list($system, $user) = ds_survey_ai_build_prompt($answers, $analysis);

    $body = [
        'model'      => $model,
        'max_tokens' => 2048,
        'thinking'   => ['type' => 'adaptive'],
        'output_config' => [
            'effort' => 'medium',
            'format' => ['type' => 'json_schema', 'schema' => ds_survey_ai_quote_schema()],
        ],
        'system'   => $system,
        'messages' => [['role' => 'user', 'content' => $user]],
    ];

    $response = wp_remote_post('https://api.anthropic.com/v1/messages', [
        'timeout' => 90,
        'headers' => [
            'content-type'      => 'application/json',
            'x-api-key'         => ds_survey_ai_api_key(),
            'anthropic-version' => '2023-06-01',
        ],
        'body' => wp_json_encode($body),
    ]);

    if (is_wp_error($response)) return $response;

    $code = wp_remote_retrieve_response_code($response);
    $data = json_decode(wp_remote_retrieve_body($response), true);
    if ($code !== 200 || !is_array($data)) {
        $message = $data['error']['message'] ?? ('HTTP ' . $code);
        return new WP_Error('ds_ai_http', 'Claude API error: ' . $message);
    }
    if (($data['stop_reason'] ?? '') === 'refusal') {
        return new WP_Error('ds_ai_refusal', 'The model declined this request.');
    }

    // Adaptive thinking may put a thinking block first — find the text block.
    $text = '';
    foreach ($data['content'] ?? [] as $block) {
        if (($block['type'] ?? '') === 'text') {
            $text = $block['text'];
            break;
        }
    }
    $quote = json_decode($text, true);
    if (!is_array($quote) || empty($quote['recommendations'])) {
        return new WP_Error('ds_ai_parse', 'Could not parse the generated quote.');
    }
    return $quote;
}

/**
 * Plain-text rendering of a quote for the Survey Entry record.
 */
function ds_survey_ai_quote_text($quote) {
    $lines = ['== AI-Generated Preliminary Quote ==', $quote['summary'], ''];
    foreach ($quote['recommendations'] as $i => $rec) {
        $lines[] = sprintf('%d. %s — %s', $i + 1, $rec['service'], $rec['investment']);
        $lines[] = '    ' . $rec['rationale'];
    }
    $lines[] = '';
    $lines[] = 'Total: ' . $quote['total_monthly_investment'];
    $lines[] = 'Expected outcomes: ' . $quote['expected_outcomes'];
    $lines[] = 'Next step: ' . $quote['next_step'];
    return implode("\n", $lines);
}

// ── AJAX: generate quote for a just-submitted entry ──────────
add_action('wp_ajax_ds_survey_quote', 'ds_survey_handle_quote_request');
add_action('wp_ajax_nopriv_ds_survey_quote', 'ds_survey_handle_quote_request');

function ds_survey_handle_quote_request() {
    if (!ds_survey_ai_enabled()) {
        wp_send_json_error(['message' => 'Quote generation is not available.'], 400);
    }

    $entry_id = absint($_POST['entry'] ?? 0);
    $token    = sanitize_text_field(wp_unslash($_POST['token'] ?? ''));
    $entry    = $entry_id ? get_post($entry_id) : null;

    // The token is minted at submit time and expires shortly after, so only
    // the visitor who just submitted this entry can trigger a generation.
    $stored  = (string) get_post_meta($entry_id, '_ds_quote_token', true);
    $expires = (int) get_post_meta($entry_id, '_ds_quote_token_expires', true);
    if (!$entry || $entry->post_type !== 'ds_survey_entry'
        || $token === '' || !hash_equals($stored, $token) || time() > $expires) {
        wp_send_json_error(['message' => 'Invalid or expired request.'], 403);
    }

    // One generation per entry — replays get the cached quote.
    $cached = get_post_meta($entry_id, '_ds_survey_quote', true);
    if (is_array($cached) && $cached) {
        wp_send_json_success(['quote' => $cached]);
    }

    // Per-IP throttle as a cost backstop.
    $ip  = sanitize_text_field($_SERVER['REMOTE_ADDR'] ?? '');
    $key = 'ds_quote_rl_' . md5($ip);
    $hits = (int) get_transient($key);
    if ($hits >= 3) {
        wp_send_json_error(['message' => 'Too many requests. Please try again later.'], 429);
    }
    set_transient($key, $hits + 1, HOUR_IN_SECONDS);

    $answers = get_post_meta($entry_id, '_ds_survey_answers', true);
    if (!is_array($answers)) {
        wp_send_json_error(['message' => 'Entry data unavailable.'], 400);
    }

    $quote = ds_survey_ai_generate_quote($answers, ds_survey_analyze($answers));
    if (is_wp_error($quote)) {
        error_log('[ds-survey] AI quote failed for entry ' . $entry_id . ': ' . $quote->get_error_message());
        wp_send_json_error(['message' => "We couldn't generate your quote automatically — we'll include it when we follow up."], 502);
    }

    // Persist to the entry for the team.
    update_post_meta($entry_id, '_ds_survey_quote', $quote);
    delete_post_meta($entry_id, '_ds_quote_token');
    wp_update_post([
        'ID'           => $entry_id,
        'post_content' => $entry->post_content . "\n\n" . ds_survey_ai_quote_text($quote),
    ]);

    wp_send_json_success(['quote' => $quote]);
}
